server:
  port: 9002
spring:
  profiles: # ??? ???? ??, ??? ? ???? ??.
    active: gateway
  application:
    name: gateway
  config:
    import: optional:configserver:http://config.taskoo.net
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          # uri: http://localhost:4003 # 포워딩할 주소, http://localhost:9002/user 로 들어오면 http://localhost:4003/user 로 포워딩
          predicates:
            - Path=/user/**
          filters:
            - CustomAuthFilter
        - id: user-api
          uri: lb://user
          # uri: http://localhost:4003/api # 포워딩할 주소, http://localhost:9002/api/user 로 들어오면 http://localhost:4003/api/user 로 포워딩
          predicates:
            - Path=/api/user/**
          filters:
            - CustomAuthFilter


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone : http://localhost:8761/eureka
      # defaultZone: http://eureka.taskoo.net/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"