server:
  port: 8034
spring:
  profiles: # ??? ???? ??, ??? ? ???? ??.
    active: gateway
  application:
    name: config
  config:
    import: optional:configserver:http://config.taskoo.net
management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka.taskoo.net/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"