server:
  port: 9002
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
<<<<<<< HEAD
        - id: service1
          uri: lb://SERVICE1
          predicates:
            - Path=/services/**
        - id: service31
          uri: lb://SERVICE31
          predicates:
            - Path=/client/**
        - id: gateway
          uri: lb://GATEWAY
=======
        - id: service31
          uri: http://client.taskoo.net
          predicates:
            - Path=/form/**
        - id: gateway
          uri: http://gateway.taskoo.net
>>>>>>> 80bffa6c0cee9b2571f7d29e1a3fbabb0ab40a69
          predicates:
            - Path=/gateway/**
        - id: test-service
          predicates:
            - Path=/first-service/**
          uri: lb://SERVICE1
          filters:
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
<<<<<<< HEAD

=======
>>>>>>> 80bffa6c0cee9b2571f7d29e1a3fbabb0ab40a69
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka.taskoo.net/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"