apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: springboot
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      version: v1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      containers:
        - name: gateway
          image: harbor.aikoo.net/tanzu/gateway:1.11
          ports:
            - containerPort: 9002